### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by LoyVanBeek** [tue-robotics/snowboy_ros#1]
Did you forget to add a .h file?

`In file included from /home/loy/ros/indigo/system/src/snowboy_ros/src/hotword_detector.cpp:3:0:
/home/loy/ros/indigo/system/src/snowboy_ros/include/snowboy_ros/hotword_detector.h:4:44: fatal error: snowboy/include/snowboy-detect.h: No such file or directory
 #include <snowboy/include/snowboy-detect.h>
`

**Comment by LoyVanBeek** [comment]
To fix, run 
```bash
git submodule init
git submodule update
```

as Snowboy itself is included as a submodule

**Comment by rokusottervanger** [comment]
I'll make sure the target does a clone --recursive so the submodule is checked out automatically
